version: '2'

services:
    web:
        image: nginx:latest
        container_name: "mutant_nginx"
        ports:
            - "80:80"
        volumes:
            - ./:/mutant
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        networks:
            mutant-network:
                ipv4_address: 172.18.0.2
        links:
            - php
    php:
        build: php-fpm
        container_name: "mutant_php"
        volumes:
            - ./:/mutant
        networks:
            mutant-network:
                ipv4_address: 172.18.0.3
        links:
            - db

    db:
        image: mysql
        container_name : "mutant_mysql"
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: xmennotallowed123
            MYSQL_DATABASE: mutant_db
        networks:
            mutant-network:
                ipv4_address: 172.18.0.4

networks:
    mutant-network:
        external: true
